-- ============================================================
--  TRUNCATE ALL TABLES — Tlahtolli  [PostgreSQL]
--  Limpia el contenido sin eliminar las tablas ni el schema.
--  El orden importa: primero las tablas hijo, luego las padre.
--  TRUNCATE con RESTART IDENTITY resetea las secuencias (SERIAL).
-- ============================================================

-- ── 1. Tablas hoja (no tienen hijos) ─────────────────────────
TRUNCATE TABLE TA_LESSON_HISTORY    RESTART IDENTITY CASCADE;
TRUNCATE TABLE TA_USER_ACHIEVEMENTS RESTART IDENTITY CASCADE;
TRUNCATE TABLE TA_USER_ENERGY       RESTART IDENTITY CASCADE;
TRUNCATE TABLE TA_USER_PROGRESS     RESTART IDENTITY CASCADE;
TRUNCATE TABLE TA_USER_STATS        RESTART IDENTITY CASCADE;
TRUNCATE TABLE RL_UNIT_VOCAB        RESTART IDENTITY CASCADE;
TRUNCATE TABLE CT_WRITING_SYSTEMS   RESTART IDENTITY CASCADE;

-- ── 2. Ejercicios y lecciones ────────────────────────────────
TRUNCATE TABLE CT_EXERCISES RESTART IDENTITY CASCADE;
TRUNCATE TABLE CT_LESSONS   RESTART IDENTITY CASCADE;

-- ── 3. Estructura de contenido ───────────────────────────────
TRUNCATE TABLE CT_VOCABULARY RESTART IDENTITY CASCADE;
TRUNCATE TABLE CT_UNITS      RESTART IDENTITY CASCADE;
TRUNCATE TABLE CT_LEVELS     RESTART IDENTITY CASCADE;

-- ── 4. Logros ────────────────────────────────────────────────
TRUNCATE TABLE CT_ACHIEVEMENTS RESTART IDENTITY CASCADE;

-- ── 5. Tablas raíz ───────────────────────────────────────────
TRUNCATE TABLE TA_USERS     RESTART IDENTITY CASCADE;
TRUNCATE TABLE CT_LANGUAGES RESTART IDENTITY CASCADE;

-- Verificar que todas quedaron vacías
SELECT 'CT_LANGUAGES'         AS TABLA, COUNT(*) AS FILAS FROM CT_LANGUAGES        UNION ALL
SELECT 'TA_USERS'             AS TABLA, COUNT(*) AS FILAS FROM TA_USERS             UNION ALL
SELECT 'TA_USER_ENERGY'       AS TABLA, COUNT(*) AS FILAS FROM TA_USER_ENERGY       UNION ALL
SELECT 'TA_USER_STATS'        AS TABLA, COUNT(*) AS FILAS FROM TA_USER_STATS        UNION ALL
SELECT 'CT_LEVELS'            AS TABLA, COUNT(*) AS FILAS FROM CT_LEVELS            UNION ALL
SELECT 'CT_UNITS'             AS TABLA, COUNT(*) AS FILAS FROM CT_UNITS             UNION ALL
SELECT 'CT_VOCABULARY'        AS TABLA, COUNT(*) AS FILAS FROM CT_VOCABULARY        UNION ALL
SELECT 'RL_UNIT_VOCAB'        AS TABLA, COUNT(*) AS FILAS FROM RL_UNIT_VOCAB        UNION ALL
SELECT 'CT_EXERCISES'         AS TABLA, COUNT(*) AS FILAS FROM CT_EXERCISES         UNION ALL
SELECT 'CT_LESSONS'           AS TABLA, COUNT(*) AS FILAS FROM CT_LESSONS           UNION ALL
SELECT 'CT_WRITING_SYSTEMS'   AS TABLA, COUNT(*) AS FILAS FROM CT_WRITING_SYSTEMS   UNION ALL
SELECT 'CT_ACHIEVEMENTS'      AS TABLA, COUNT(*) AS FILAS FROM CT_ACHIEVEMENTS      UNION ALL
SELECT 'TA_USER_ACHIEVEMENTS' AS TABLA, COUNT(*) AS FILAS FROM TA_USER_ACHIEVEMENTS UNION ALL
SELECT 'TA_USER_PROGRESS'     AS TABLA, COUNT(*) AS FILAS FROM TA_USER_PROGRESS     UNION ALL
SELECT 'TA_LESSON_HISTORY'    AS TABLA, COUNT(*) AS FILAS FROM TA_LESSON_HISTORY;

-- ── ------------- ───────────────────────────────────────────
DROP TABLE IF EXISTS TA_LESSON_HISTORY     CASCADE;
DROP TABLE IF EXISTS TA_USER_ACHIEVEMENTS  CASCADE;
DROP TABLE IF EXISTS TA_USER_ENERGY        CASCADE;
DROP TABLE IF EXISTS TA_USER_PROGRESS      CASCADE;
DROP TABLE IF EXISTS RL_UNIT_VOCAB         CASCADE;
DROP TABLE IF EXISTS CT_EXERCISES          CASCADE;
DROP TABLE IF EXISTS CT_WRITING_SYSTEMS    CASCADE;
DROP TABLE IF EXISTS CT_VOCABULARY         CASCADE;
DROP TABLE IF EXISTS CT_UNITS              CASCADE;
DROP TABLE IF EXISTS CT_LEVELS             CASCADE;
DROP TABLE IF EXISTS TA_USER_STATS         CASCADE;
DROP TABLE IF EXISTS TA_USERS              CASCADE;
DROP TABLE IF EXISTS CT_LANGUAGES          CASCADE;
DROP TABLE IF EXISTS CT_ACHIEVEMENTS       CASCADE;
DROP TABLE IF EXISTS CT_LESSONS            CASCADE;

