spring.application.name=ar-cs-tlahtolcalli

server.port=7575

# spring.jpa.hibernate.ddl-auto=validate
 spring.jpa.properties.hibernate.default_schema=sc_myschema
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.format_sql=false

