spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: System
    password: Cesar25garcia
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format-sql: true

server:
  port: 7575